version: "3"
services:
  web:
    image: nginx:alpine
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "56333:80"
    volumes:
      - ".:/usr/share/nginx/html:ro"
    networks:
      - webnet
networks:
  webnet:
